Project/Project/Controllers/LeadershipController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using Project.Filters;
using Project.Methods;
using Project.Models;

namespace Project.Controllers
{
    [Culture]
    public class LeadershipController : Controller
    {
        //
        // GET: /Leadership/
        public ActionResult Show()
        {
            var leades = LeadershipMethods.GetAll();
            return View(leades);
        }

        public ActionResult AddLeader()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult AddLeader(LeaderView model, HttpPostedFileBase photo)
        {
            if (!ModelState.IsValid) return View(model);
            if (photo == null)
            {
                ModelState.AddModelError("Error", Resources.I18n.NoFile);
                return View(model);
            }
            LeadershipMethods.SaveLeader(model, LeadershipMethods.SaveImage(photo));
            return RedirectToAction("Show");
        }

        [Authorize(Roles = "Admin")]
        public ActionResult RemoveLeader(int leaderId)
        {
            var returnUrl = Request.UrlReferrer.OriginalString;
            LeadershipMethods.RemoveLeader(leaderId);
            return Redirect(returnUrl);
        }
	}
}

Project/Project/Controllers/StaticController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project.Filters;
using Project.Methods;
using Project.Models;
using Resources;

namespace Project.Controllers
{
     [Culture]
    public class StaticController : Controller
    {
        //
        // GET: /Static/
         public ActionResult Redactor(string header)
         {
             var model = StaticsMethod.FindStatics(header);
             ViewBag.Header = header;
             return View(model);
         }
         [HttpPost]
         public ActionResult Redactor(Statics statics)
         {
             StaticsMethod.SaveStatics(statics);
             return RedirectToAction("Index", "Home");
         }
         public ActionResult History()
         {
             var model = StaticsMethod.FindStatics("History");
             ViewBag.Header = I18n.HistoryPage;
             if (model.Body != null)
             {
                 var str = model.Body.Split('%');
                 ViewBag.Body = str;
                 ViewBag.Size = str.Count();
             }
             else { ViewBag.Body = null; ViewBag.Size = 0; }
             return View("ShowPage", model);
         }
         public ActionResult Rest()
         {
             var model = StaticsMethod.FindStatics("Rest");
             ViewBag.Header = I18n.Rest;
             if (model.Body != null)
             {
                 var str = model.Body.Split('%');
                 ViewBag.Body = str;
                 ViewBag.Size = str.Count();
             }
             else { ViewBag.Body = null; ViewBag.Size = 0; }
             return View("ShowPage", model);
         }
         public ActionResult Mode()
         {
             var model = StaticsMethod.FindStatics("Mode");
             ViewBag.Header = I18n.Mode;
             if (model.Body != null)
             {
                 var str = model.Body.Split('%');
                 ViewBag.Body = str;
                 ViewBag.Size = str.Count();
             }
             else { ViewBag.Body = null; ViewBag.Size = 0; }
             return View("ShowPage", model);
         }
         public ActionResult Reception()
         {
             var model = StaticsMethod.FindStatics("Reception of Citizen");
             ViewBag.Header = I18n.Reception;
             if (model.Body != null)
             {
                 var str = model.Body.Split('%');
                 ViewBag.Body = str;
                 ViewBag.Size = str.Count();
             }
             else { ViewBag.Body = null; ViewBag.Size = 0; }
             return View("ShowPage", model);
         }
         public ActionResult Procedure()
         {
             var model = StaticsMethod.FindStatics("Administrative Procedure");
             ViewBag.Header = I18n.Procedure;
             if (model.Body != null)
             {
                 var str = model.Body.Split('%');
                 ViewBag.Body = str;
                 ViewBag.Size = str.Count();
             }
             else { ViewBag.Body = null; ViewBag.Size = 0; }
             return View("ShowPage", model);
         }
         public ActionResult OneWindow()
         {
             var model = StaticsMethod.FindStatics("One Window");
             ViewBag.Header = I18n.OneWindow;
             if (model.Body != null)
             {
                 var str = model.Body.Split('%');
                 ViewBag.Body = str;
                 ViewBag.Size = str.Count();
             }
             else { ViewBag.Body = null; ViewBag.Size = 0; }
             return View("ShowPage", model);
         }
         public ActionResult Privatization()
         {
             var model = StaticsMethod.FindStatics("Privatization");
             ViewBag.Header = I18n.Privatization;
             if (model.Body != null)
             {
                 var str = model.Body.Split('%');
                 ViewBag.Body = str;
                 ViewBag.Size = str.Count();
             }
             else { ViewBag.Body = null; ViewBag.Size = 0; }
             return View("ShowPage", model);
         }
         public ActionResult YrUslugi()
         {
             var model = StaticsMethod.FindStatics("YrUslgi");
             ViewBag.Header = I18n.YrUslugi;
             if (model.Body != null)
             {
                 var str = model.Body.Split('%');
                 ViewBag.Body = str;
                 ViewBag.Size = str.Count();
             }
             else { ViewBag.Body = null; ViewBag.Size = 0; }
             return View("ShowPage", model);
         }
         public ActionResult Contacts()
         {
             var model = StaticsMethod.FindStatics("Contacts");
             ViewBag.Header = I18n.Contacts;
             if (model.Body != null)
             {
                 var str = model.Body.Split('%');
                 ViewBag.Body = str;
                 ViewBag.Size = str.Count();
             }
             else { ViewBag.Body = null; ViewBag.Size = 0; }
             return View("ShowPage", model);
         }
         public ActionResult Dispatcher()
         {
             var model = StaticsMethod.FindStatics("dispatcher");
             ViewBag.Header = I18n.Dispatcher;
             if (model.Body != null)
             {
                 var str = model.Body.Split('%');
                 ViewBag.Body = str;
                 ViewBag.Size = str.Count();
             }
             else
             {
                 ViewBag.Body = null;
                 ViewBag.Size = 0;
             }
             return View("ShowPage", model);
         }
    }
}

Project/Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title</title>
        @Styles.Render("~/Content/css")
        @Styles.Render("~/Content/owl")
        @Styles.Render("~/Content/tabs")
        @Styles.Render("~/Content/inputs")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @Scripts.Render("~/bundles/menu")
        @Scripts.Render("~/bundles/owl")
        @Scripts.Render("~/bundles/tabs")
        @Scripts.Render("~/bundles/jqueryval")
        
    </head>
    <body>
        @Html.Partial("_Menu")
        <hr/>
        <div class="container">
            @RenderBody()
        </div>
        @RenderSection("scripts", required: false)
    
    </body>
</html>

Project/Project/Views/Shared/_Menu.cshtml
<div class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <span class="navbar-brand">
                <a href="@Url.Action("Index", "Home")"><i class="glyphicon glyphicon-home"></i>@Resources.I18n.MainPage</a>
            </span>
        </div>
        <div class="divider"></div>
        <ul class="nav navbar-nav">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true">
                    @Resources.I18n.OneWindow
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                    <li>
                        <a href='@Url.Action("OneWindow", "Static")'>@Resources.I18n.OneWindow</a>
                    </li>

                    <li>
                        <a href='@Url.Action("Show", "Documents", new {type = DocsTypes.Blank})'>@I18n.Blanks</a>
                    </li>

                    <li>
                        <a href='@Url.Action("Procedure", "Static")'>@Resources.I18n.Procedure</a>
                    </li>
                    <li class="dropdown-submenu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            @Resources.I18n.ElectronicReception
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href='@Url.Action("AddReception", "Reception", new {@type = "YL"})'>@Resources.I18n.LegalPerson</a>
                            </li>

                            <li>
                                <a href='@Url.Action("AddReception", "Reception", new {@type = "FL"})'>@Resources.I18n.PhysicalPerson</a>
                            </li>

                        </ul>
                    </li>

                </ul>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                    <i class="glyphicon glyphicon-folder-open"></i>
                    @Resources.I18n.Services
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                    <li>
                        <a href='@Url.Action("Rest", "Static")'>@Resources.I18n.Rest</a>
                    </li>
                    <li>
                        <a href='@Url.Action("Privatization", "Static")'>@Resources.I18n.Privatization</a>
                    </li>
                    <li>
                        <a href='@Url.Action("YrUslugi", "Static")'>@Resources.I18n.YrUslugi</a>
                    </li>
                </ul>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                    @I18n.AboutUs
                </a>
                <ul class="dropdown-menu" role="menu">
                    <li>
                        <a href='@Url.Action("History", "Static")'>@Resources.I18n.HistoryPage</a>
                    </li>
                    <li>
                        <a href='@Url.Action("Show", "Leadership")'>@Resources.I18n.Leadership</a>
                    </li>
                    <li>
                        <a href='@Url.Action("Mode", "Static")'>@Resources.I18n.Mode</a>
                    </li>
                    <li>
                        <a href='@Url.Action("Reception", "Static")'>@Resources.I18n.Reception</a>
                    </li>
                    <li>

                        <a href='@Url.Action("Show", "Documents", new {type = DocsTypes.File})'>@I18n.RegulatoryDocuments</a>
                    </li>
                    <li>
                        <a href='@Url.Action("ShowAllJobs", "Jobs")'>@Resources.I18n.Jobs</a>
                    </li>
                    <li>
                        <a href='@Url.Action("Dispatcher", "Static")'>@Resources.I18n.Dispatcher</a>
                    </li>
                    <li>
                        <a href='@Url.Action("Contacts", "Static")'>@Resources.I18n.Contacts</a>
                    </li>
                </ul>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            @Html.Partial("_LoginPartial")
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" style="padding: 10px;">
                    @if (Culture.Contains("ru"))
                    {
                        <img src="/Content/CultureItem/ru.png" height="40px"/>
                    }
                    else if (Culture.Contains("en"))
                    {
                        <img src="/Content/CultureItem/en.png" height="40px"/>
                    }
                    else
                    {
                        <img src="/Content/CultureItem/by.png" height="40px"/>
                    }
                </a>
                <ul class="dropdown-menu" role="menu">
                    <li>
                        <a style="padding: 3px;" href='@Url.Action("ChangeCulture", "Home", new {@language = "ru"}, null)'>
                            <img src="/Content/CultureItem/ru.png"/>
                        </a>
                    </li>
                    <li>
                        <a style="padding: 3px;" href='@Url.Action("ChangeCulture", "Home", new {@language = "be"}, null)'>
                            <img src="/Content/CultureItem/by.png"/>
                        </a>
                    </li>
                    <li>
                        <a style="padding: 3px;" href='@Url.Action("ChangeCulture", "Home", new {@language = "en"}, null)'>
                            <img src="/Content/CultureItem/en.png"/>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>

<script>
    $(document).ready(function() {
        $('.nav li.dropdown').hover(function() {
            $(this).addClass('open');
        }, function() {
            $(this).removeClass('open');
        });
    });
</script>

Project/Project/Views/Shared/_ModalWindow.cshtml
<div class="modal fade" id="modalWindow" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        </div>
    </div>
</div>