Project/Project/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project.Filters;
using Project.Methods;
using Project.Models;

namespace Project.Controllers
{
    [Culture]
    public class JobsController : Controller
    {
         [Authorize(Roles = "Admin")]
        public ActionResult AddJobs()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult AddJobs(JobsView jobsView)
        {
          
            if (!ModelState.IsValid)
            {
                return View(jobsView);
            }
            JobsMethods.SaveJobs(jobsView);
            return RedirectToAction("ShowAllJobs", "Jobs");
        }
        public ActionResult ShowAllJobs()
        {
            var jobs = new List<Jobs>();
            using (var db = new Db())
            {
                jobs = db.Jobs.ToList();
            }
            return View(jobs);
        }
        public ActionResult ShowJobs(int jobsId)
        {
            var jobs = new Jobs();
            using (var db = new Db())
            {
                jobs = db.Jobs.Find(jobsId);
            }
            return View(jobs);
        }
        public ActionResult RemoveJobs(int jobsId)
        {
            JobsMethods.RemoveJobs(jobsId);
            return RedirectToAction("ShowAllJobs", "Jobs");
        }
    }
}

Project/Project/Controllers/NewsController.cs
using System.Web;
using System.Web.Mvc;
using Project.Filters;
using Project.Methods;
using Project.Models;

namespace Project.Controllers
{
    [Culture]
    public class NewsController : Controller
    {
        //
        // GET: /News/
        public ActionResult ShowLastNews()
        {
            var list = NewsMethods.GetLastNews();
            return PartialView(list);
        }

        public ActionResult ShowAllNews()
        {
            var list = NewsMethods.GetAllNews();
            return PartialView(list);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult AddNews()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult AddNews(NewsView news, HttpPostedFileBase image)
        {
            if (!ModelState.IsValid) return View(news);
            NewsMethods.SaveNews(news, NewsMethods.SaveImage(image));
            return RedirectToAction("Index","Home");
        }

        [Authorize(Roles = "Admin")]
        public ActionResult RemoveNews(int newsId)
        {
            NewsMethods.RemoveNews(newsId);
            return RedirectToAction("Index","Home");
        }

        public ActionResult NewsView(int? newsId)
        {
            var model = NewsMethods.FindNews(newsId);      
            return View(model);
        }
	}
}

Project/Project/Views/Jobs/AddJobs.cshtml
@model JobsView

@Styles.Render("~/Content/markdown")

@section Scripts {

    @Scripts.Render("~/bundles/markdown")
}

@using (Html.BeginForm("AddJobs", "Jobs", FormMethod.Post,
    new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="col-md-offset-1 col-md-10">
        <div class="input input--juro">
            @Html.TextBoxFor(m => m.Header, new { @class = "input__field input__field--juro" })
            <div class="input__label input__label--juro ">
                @Html.LabelFor(m => m.Header, new { @class = "input__label-content input__label-content--juro" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-12">
            @Html.TextAreaFor(m => m.Body, new { @class = "form-control col-md-8" })
        </div>
    </div>
    <hr />
    <div class="form-group">
        <div class="col-md-8 col-lg-offset-2">
            <input type="submit" class="btn btn-success btn-lg col-md-12" value="@I18n.Add" />
        </div>
    </div>
}

<script>
    $(document).ready(function() {
        $("#Body")["data-provider"] = "markdown-editable";
        $("#Body").attr("placeholder",'@I18n.Field_Description');
        $("#Body").markdown({
            width: "col-md-8"
        });
        $('input[type=file]').bootstrapFileInput();
        $('.file-inputs').bootstrapFileInput();
    });

</script>

Project/Project/Views/Jobs/ShowAllJobs.cshtml
@{
    ViewBag.Title = I18n.Jobs;
}
@model List<Jobs>
<h2 class="text-center">@ViewBag.Title</h2>
@if (HttpContext.Current.User.IsInRole("Admin"))
{
    <div class="row">
        <div class="col-md-offset-5">
            <a class="btn btn-success col-md-4"href='@Url.Action("AddJobs","Jobs")'>
                <i class="glyphicon glyphicon-plus"></i> @I18n.Add
            </a>
        </div>
    </div>
    <hr/>
}
<div class="list-group col-lg-10 col-lg-offset-1">
    @foreach (var jobs in Model)
    {
        <div class="list-group-item">
            <div class="row">
                <a href="@Url.Action("ShowJobs","Jobs",new {@jobsId=jobs.Id})">
                    <div class="col-md-10" style="word-wrap: break-word; font-size: 20px">
                        <span>@jobs.Header</span>
                    </div>
                    <b class="col-md-1">
                        @jobs.Date.ToShortDateString()
                    </b>
                </a>
                @if (HttpContext.Current.User.IsInRole("Admin"))
                {
                    <div class="col-md-1 text-center">
                        <a href='@Url.Action("RemoveJobs", "Jobs",new {jobsId = jobs.Id})'>
                            <i class="glyphicon glyphicon-remove"></i>
                        </a>
                    </div>
                }
            </div>
        </div>
    }
</div>

Project/Project/Views/Jobs/ShowJobs.cshtml
@model Jobs
@if (Model == null)
{
    <h1 class="text-center text-danger">@I18n.JobsNotFound</h1>
}
else
{
    ViewBag.Title = Model.Header;
    <h1 class="text-center">@Model.Header</h1>
    <div class="col-lg-12">
        <small class="col-lg-2"><b>@Model.Date</b></small>
        @if (HttpContext.Current.User.IsInRole("Admin"))
        {
            @*<div class="col-lg-10">
                <a href='@Url.Action("RemoveNews", "News", new {newsId = Model.Id})'>
                    <i class="glyphicon glyphicon-trash"></i>
                </a>
            </div>*@
        }
    </div>
    <hr />
    <label class="col-lg-12">@Html.Markdown(Model.Body)</label>
}